### ISSUE TITLE
AssertionError: PETSc gives different solution compared to SciPy!

### ISSUE THREAD

**Issue by nico-canta** [BlueBrain/AstroVascPy#18]
Running in debug mode:

```
export DEBUG_BFS=1
```

We get the following error:
```
-> PETSc Solver [bloodflow.py] : Start
-> PETSc Solver [bloodflow.py] : End
-> PETSc residual norm = 0.00031427991521717526
-> SciPy residual norm = 3.975743898866682e-08

  0%|          | 0/5 [00:00<?, ?it/s]
  0%|          | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/cantarut/AstroVascPy/examples/simulate_OU_process.py", line 105, in <module>
    flows, pressures, radiii = simulate_ou_process(
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/cantarut/AstroVascPy/astrovascpy/bloodflow.py", line 600, in simulate_ou_process
    update_static_flow_pressure(graph, boundary_flow, BLOOD_VISCOSITY, P_BASE)
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/cantarut/AstroVascPy/astrovascpy/bloodflow.py", line 123, in update_static_flow_pressure
    solution = _solve_linear(laplacian_cc if graph else None, input_flow)
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/cantarut/AstroVascPy/astrovascpy/bloodflow.py", line 729, in _solve_linear
    assert np.allclose(
AssertionError: PETSc gives different solution compared to SciPy!
```

I tried to use several datasets, and I always got this error.

**Comment by nico-canta** [comment]
A few updates:

-  I can compute the norm of residuals in 2 ways: 
1) I simply solve the system `Ax=b` with PETSc and then I compute the l2 norm of the residuals as ||r|| = || Ax - b ||.
2) I use `ksp.getResidualNorm()`
The two values are similar but different. WHY?    This is something I need to figure out. 

- Now we are using a `GMRES` solver.  Although for singular symmetric systems it is also possible to use `CG`. 
see [link1](https://scicomp.stackexchange.com/questions/14497/solving-lx-b-for-big-sparse-laplacian-matrices?rq=1) [link2](https://scicomp.stackexchange.com/questions/35239/what-happens-when-i-use-a-conjugate-gradient-solver-with-a-symmetric-positive-se)
I need to test which is better.

**Comment by nico-canta** [comment]
2. The `kps.getResidualNorm` uses an approximate and/or preconditioned approach. It is different from the l2 norm.

After many experiments:
- GMRES and CG both work well with our singular system. 
- GAMG preconditioner is the best.  
- The best choice so far was LGMRES.
- Informing PETSc that we are using a singular matrix is helpful.  This is done by creating the null-space of the laplacian. In this way we are using a more efficient algorithm.

**Comment by nico-canta** [comment]
Now we set `scipy` as the default solver.
- For small circuits (e.g. the rat) it is better to use scipy. Direct methods work well and are faster.
- For big circuits (e.g. the mouse) it is better to use petsc. Simply because direct methods don't work.
